/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarPipelinesRouteImport } from './../routes/_sidebar/pipelines'
import { Route as SidebarGovernanceRouteImport } from './../routes/_sidebar/governance'
import { Route as SidebarGenieRouteImport } from './../routes/_sidebar/genie'
import { Route as SidebarClientJourneyRouteImport } from './../routes/_sidebar/client-journey'
import { Route as SidebarAuditLogRouteImport } from './../routes/_sidebar/audit-log'
import { Route as SidebarAnalyticsRouteImport } from './../routes/_sidebar/analytics'
import { Route as SidebarClientClientIdRouteImport } from './../routes/_sidebar/client.$clientId'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarPipelinesRoute = SidebarPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarGovernanceRoute = SidebarGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarGenieRoute = SidebarGenieRouteImport.update({
  id: '/genie',
  path: '/genie',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarClientJourneyRoute = SidebarClientJourneyRouteImport.update({
  id: '/client-journey',
  path: '/client-journey',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAuditLogRoute = SidebarAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAnalyticsRoute = SidebarAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarClientClientIdRoute = SidebarClientClientIdRouteImport.update({
  id: '/client/$clientId',
  path: '/client/$clientId',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof SidebarAnalyticsRoute
  '/audit-log': typeof SidebarAuditLogRoute
  '/client-journey': typeof SidebarClientJourneyRoute
  '/genie': typeof SidebarGenieRoute
  '/governance': typeof SidebarGovernanceRoute
  '/pipelines': typeof SidebarPipelinesRoute
  '/profile': typeof SidebarProfileRoute
  '/client/$clientId': typeof SidebarClientClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof SidebarAnalyticsRoute
  '/audit-log': typeof SidebarAuditLogRoute
  '/client-journey': typeof SidebarClientJourneyRoute
  '/genie': typeof SidebarGenieRoute
  '/governance': typeof SidebarGovernanceRoute
  '/pipelines': typeof SidebarPipelinesRoute
  '/profile': typeof SidebarProfileRoute
  '/client/$clientId': typeof SidebarClientClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/analytics': typeof SidebarAnalyticsRoute
  '/_sidebar/audit-log': typeof SidebarAuditLogRoute
  '/_sidebar/client-journey': typeof SidebarClientJourneyRoute
  '/_sidebar/genie': typeof SidebarGenieRoute
  '/_sidebar/governance': typeof SidebarGovernanceRoute
  '/_sidebar/pipelines': typeof SidebarPipelinesRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/client/$clientId': typeof SidebarClientClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit-log'
    | '/client-journey'
    | '/genie'
    | '/governance'
    | '/pipelines'
    | '/profile'
    | '/client/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit-log'
    | '/client-journey'
    | '/genie'
    | '/governance'
    | '/pipelines'
    | '/profile'
    | '/client/$clientId'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/analytics'
    | '/_sidebar/audit-log'
    | '/_sidebar/client-journey'
    | '/_sidebar/genie'
    | '/_sidebar/governance'
    | '/_sidebar/pipelines'
    | '/_sidebar/profile'
    | '/_sidebar/client/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/pipelines': {
      id: '/_sidebar/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof SidebarPipelinesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/governance': {
      id: '/_sidebar/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof SidebarGovernanceRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/genie': {
      id: '/_sidebar/genie'
      path: '/genie'
      fullPath: '/genie'
      preLoaderRoute: typeof SidebarGenieRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/client-journey': {
      id: '/_sidebar/client-journey'
      path: '/client-journey'
      fullPath: '/client-journey'
      preLoaderRoute: typeof SidebarClientJourneyRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/audit-log': {
      id: '/_sidebar/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof SidebarAuditLogRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/analytics': {
      id: '/_sidebar/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof SidebarAnalyticsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/client/$clientId': {
      id: '/_sidebar/client/$clientId'
      path: '/client/$clientId'
      fullPath: '/client/$clientId'
      preLoaderRoute: typeof SidebarClientClientIdRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarAnalyticsRoute: typeof SidebarAnalyticsRoute
  SidebarAuditLogRoute: typeof SidebarAuditLogRoute
  SidebarClientJourneyRoute: typeof SidebarClientJourneyRoute
  SidebarGenieRoute: typeof SidebarGenieRoute
  SidebarGovernanceRoute: typeof SidebarGovernanceRoute
  SidebarPipelinesRoute: typeof SidebarPipelinesRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarClientClientIdRoute: typeof SidebarClientClientIdRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarAnalyticsRoute: SidebarAnalyticsRoute,
  SidebarAuditLogRoute: SidebarAuditLogRoute,
  SidebarClientJourneyRoute: SidebarClientJourneyRoute,
  SidebarGenieRoute: SidebarGenieRoute,
  SidebarGovernanceRoute: SidebarGovernanceRoute,
  SidebarPipelinesRoute: SidebarPipelinesRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarClientClientIdRoute: SidebarClientClientIdRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
